import type { Config } from "tailwindcss";

/** Stitch / Obsidian Terminal — 源自 `素材/官网设计/2/stitch` + axiom_terminal/DESIGN.md */
const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0e0e0e",
        surface: "#0e0e0e",
        "surface-dim": "#0e0e0e",
        "surface-container": "#1a1919",
        "surface-container-low": "#131313",
        "surface-container-high": "#201f1f",
        "surface-container-highest": "#262626",
        "surface-variant": "#262626",
        "surface-bright": "#2c2c2c",
        "surface-container-lowest": "#000000",
        "on-background": "#ffffff",
        "on-surface": "#ffffff",
        "on-surface-variant": "#adaaaa",
        primary: "#85adff",
        "primary-dim": "#699cff",
        "primary-fixed": "#6e9fff",
        "primary-fixed-dim": "#5391ff",
        "primary-container": "#6e9fff",
        "on-primary": "#002c66",
        "on-primary-container": "#002150",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#002a62",
        secondary: "#00fd87",
        "secondary-dim": "#00ed7e",
        "secondary-fixed": "#00fd87",
        "secondary-fixed-dim": "#00ed7e",
        "secondary-container": "#006d37",
        "on-secondary": "#005b2c",
        "on-secondary-container": "#e3ffe4",
        "on-secondary-fixed": "#004621",
        "on-secondary-fixed-variant": "#006632",
        tertiary: "#ff716b",
        "tertiary-dim": "#ff716b",
        "tertiary-fixed": "#ff928b",
        "tertiary-fixed-dim": "#ff7b74",
        "tertiary-container": "#ff4d4d",
        "on-tertiary": "#490005",
        "on-tertiary-container": "#1f0001",
        "on-tertiary-fixed": "#3a0003",
        "on-tertiary-fixed-variant": "#79000f",
        error: "#ff716c",
        "error-dim": "#d7383b",
        "error-container": "#9f0519",
        "on-error": "#490006",
        "on-error-container": "#ffa8a3",
        outline: "#777575",
        "outline-variant": "#494847",
        "inverse-surface": "#fcf8f8",
        "inverse-on-surface": "#565554",
        "inverse-primary": "#005bc4",
        "surface-tint": "#85adff",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        jetbrains: ["var(--font-jetbrains)", "ui-monospace", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      keyframes: {
        "pulse-live": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "pulse-live": "pulse-live 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;
